import { Type, type Static } from "@sinclair/typebox";

import {
  DigestSchema,
  IdentifierSchema,
  LocatorSchema,
  TimestampSchema,
  enumerated,
  strictObject,
} from "./common.js";
import { recordEnvelopeSchema } from "./envelope.js";

/**
 * DesignSet schemas (designset lifecycle design 7 and 9, plan T11). The
 * proposal is an untrusted runtime record — it never enters the materialized
 * graph before human approval — so every shape is strict, every enum closed
 * and every artifact body validated against its per-kind profile. Semantic
 * relations are limited to ADDRESSES / SHAPES / SPECIFIES; DERIVES_FROM and
 * CONTAINS structure edges are generated by the committer, never proposed.
 */
export const DESIGN_ARTIFACT_KINDS = [
  "api_contract",
  "data_contract",
  "test_strategy",
  "ui_design",
] as const;
export type DesignArtifactKind = (typeof DESIGN_ARTIFACT_KINDS)[number];

export const DESIGN_ARTIFACT_BODY_FORMATS = [
  "structured",
  "markdown",
  "openapi",
  "json_schema",
] as const;

export const DESIGN_ASSET_NODE_TYPES = ["Decision", "Component", "DesignArtifact"] as const;
export type DesignAssetNodeType = (typeof DESIGN_ASSET_NODE_TYPES)[number];

export const DESIGN_SEMANTIC_RELATIONS = ["ADDRESSES", "SHAPES", "SPECIFIES"] as const;
export type DesignSemanticRelation = (typeof DESIGN_SEMANTIC_RELATIONS)[number];

export const DESIGN_SET_MODES = ["change", "reuse"] as const;

export const DESIGN_RISK_LEVELS = ["low", "medium", "high", "critical"] as const;

const nonEmptyString = Type.String({ minLength: 1 });

/** api_contract bodies describe protocol, operations, io, errors, compatibility. */
export const ApiContractBodySchema = strictObject({
  protocol: nonEmptyString,
  operations: Type.Array(nonEmptyString, { minItems: 1 }),
  inputs: Type.Array(nonEmptyString),
  outputs: Type.Array(nonEmptyString),
  errors: Type.Array(nonEmptyString),
  compatibility: nonEmptyString,
});
export type ApiContractBody = Static<typeof ApiContractBodySchema>;

/** data_contract bodies describe entities, constraints, invariants, migrations. */
export const DataContractBodySchema = strictObject({
  entities: Type.Array(nonEmptyString, { minItems: 1 }),
  constraints: Type.Array(nonEmptyString),
  invariants: Type.Array(nonEmptyString),
  migrations: Type.Array(nonEmptyString),
  compatibility: nonEmptyString,
});
export type DataContractBody = Static<typeof DataContractBodySchema>;

export const TddPathPolicySchema = strictObject({
  test: Type.Array(nonEmptyString),
  test_config: Type.Array(nonEmptyString),
  production: Type.Array(nonEmptyString),
  immutable: Type.Array(nonEmptyString),
});
export type TddPathPolicy = Static<typeof TddPathPolicySchema>;

/**
 * Per-requirement TDD applicability inside a test_strategy artifact (design
 * 7.3): `required` pins the provable-TDD design inputs; `not_applicable` is
 * a controlled exemption that always carries a category and a non-empty
 * business reason. The Planner may narrow but never downgrade these.
 */
export const TestStrategyTddEntrySchema = strictObject({
  requirement_id: IdentifierSchema,
  applicability: Type.Union([
    strictObject({
      status: Type.Literal("required"),
      baseline_guard_gates: Type.Array(IdentifierSchema),
      target_gate: IdentifierSchema,
      test_selectors: Type.Array(nonEmptyString, { minItems: 1 }),
      failure_oracle: nonEmptyString,
      path_policy: TddPathPolicySchema,
      framework_profile_digest: DigestSchema,
      refactor_policy: nonEmptyString,
    }),
    strictObject({
      status: Type.Literal("not_applicable"),
      category: nonEmptyString,
      reason: nonEmptyString,
    }),
  ]),
});
export type TestStrategyTddEntry = Static<typeof TestStrategyTddEntrySchema>;

/** test_strategy bodies describe scenarios, levels, gates, evidence and TDD. */
export const TestStrategyBodySchema = strictObject({
  scenarios: Type.Array(nonEmptyString, { minItems: 1 }),
  test_levels: Type.Array(nonEmptyString, { minItems: 1 }),
  required_gates: Type.Array(nonEmptyString),
  required_evidence: Type.Array(nonEmptyString),
  tdd: Type.Array(TestStrategyTddEntrySchema),
});
export type TestStrategyBody = Static<typeof TestStrategyBodySchema>;

/** ui_design bodies describe flows, key states, error states, accessibility. */
export const UiDesignBodySchema = strictObject({
  user_flows: Type.Array(nonEmptyString, { minItems: 1 }),
  key_states: Type.Array(nonEmptyString),
  error_states: Type.Array(nonEmptyString),
  accessibility: Type.Array(nonEmptyString),
});
export type UiDesignBody = Static<typeof UiDesignBodySchema>;

const artifactBodyRule = (kind: DesignArtifactKind, body: unknown) => ({
  if: { properties: { artifact_kind: { const: kind } }, required: ["artifact_kind"] },
  then: { properties: { body }, required: ["body"] },
});

export const DesignArtifactContentSchema = Type.Object(
  {
    artifact_kind: enumerated(DESIGN_ARTIFACT_KINDS),
    title: nonEmptyString,
    summary: nonEmptyString,
    assumptions: Type.Array(nonEmptyString),
    acceptance_implications: Type.Array(nonEmptyString),
    body_format: enumerated(DESIGN_ARTIFACT_BODY_FORMATS),
    body: Type.Unknown(),
  },
  {
    additionalProperties: false,
    allOf: [
      artifactBodyRule("api_contract", ApiContractBodySchema),
      artifactBodyRule("data_contract", DataContractBodySchema),
      artifactBodyRule("test_strategy", TestStrategyBodySchema),
      artifactBodyRule("ui_design", UiDesignBodySchema),
    ],
  },
);
export type DesignArtifactContent = Static<typeof DesignArtifactContentSchema>;

export const DesignNodeChangeSchema = strictObject({
  action: enumerated(["create", "revise"] as const),
  node_id: IdentifierSchema,
  node_type: enumerated(DESIGN_ASSET_NODE_TYPES),
  target_revision: Type.Integer({ minimum: 1 }),
  base: Type.Optional(
    strictObject({ revision: Type.Integer({ minimum: 1 }), digest: DigestSchema }),
  ),
  locator: Type.Optional(LocatorSchema),
  proposed_extensions: Type.Record(Type.String({ minLength: 1 }), Type.Unknown()),
});
export type DesignNodeChange = Static<typeof DesignNodeChangeSchema>;

export const ReusedDesignAssetSchema = strictObject({
  node_id: IdentifierSchema,
  node_type: enumerated(DESIGN_ASSET_NODE_TYPES),
  revision: Type.Integer({ minimum: 1 }),
  digest: DigestSchema,
});
export type ReusedDesignAsset = Static<typeof ReusedDesignAssetSchema>;

export const DesignEdgeChangeSchema = strictObject({
  action: enumerated(["create", "supersede"] as const),
  edge_id: IdentifierSchema,
  relation: enumerated(DESIGN_SEMANTIC_RELATIONS),
  source_id: IdentifierSchema,
  target_id: IdentifierSchema,
  base_digest: Type.Optional(DigestSchema),
  reason: Type.Optional(nonEmptyString),
});
export type DesignEdgeChange = Static<typeof DesignEdgeChangeSchema>;

export const DesignRiskSummarySchema = strictObject({
  level: enumerated(DESIGN_RISK_LEVELS),
  reasons: Type.Array(nonEmptyString),
});
export type DesignRiskSummary = Static<typeof DesignRiskSummarySchema>;

export const DesignApplicabilitySchema = Type.Union([
  strictObject({
    status: enumerated(["covered", "reused"] as const),
    asset_ids: Type.Array(IdentifierSchema, { minItems: 1 }),
  }),
  strictObject({ status: Type.Literal("not_applicable"), reason: nonEmptyString }),
]);
export type DesignApplicability = Static<typeof DesignApplicabilitySchema>;

export const TestStrategyCoverageBindingSchema = strictObject({
  acceptance_criterion_id: IdentifierSchema,
  test_node_id: IdentifierSchema,
  primary_test_strategy_id: IdentifierSchema,
});
export type TestStrategyCoverageBinding = Static<typeof TestStrategyCoverageBindingSchema>;

/** Per-requirement design coverage (design 9.1). */
export const RequirementDesignCoverageSchema = strictObject({
  requirement_id: IdentifierSchema,
  decision_ids: Type.Array(IdentifierSchema),
  component_scope: Type.Union([
    strictObject({
      status: enumerated(["covered", "reused"] as const),
      component_ids: Type.Array(IdentifierSchema, { minItems: 1 }),
    }),
    strictObject({ status: Type.Literal("not_applicable"), reason: nonEmptyString }),
  ]),
  test_strategy_coverage: Type.Array(TestStrategyCoverageBindingSchema),
  supporting_test_strategy_ids: Type.Array(IdentifierSchema),
  applicability: strictObject({
    api: DesignApplicabilitySchema,
    data: DesignApplicabilitySchema,
    ui: DesignApplicabilitySchema,
  }),
});
export type RequirementDesignCoverage = Static<typeof RequirementDesignCoverageSchema>;

/** The approved semantic content of a DesignSet (design 7.5). */
export const DesignSetContentSchema = strictObject({
  requirement_baseline_digest: DigestSchema,
  impact_set_id: IdentifierSchema,
  impact_set_digest: DigestSchema,
  policy_digest: DigestSchema,
  repository_baseline: nonEmptyString,
  mode: enumerated(DESIGN_SET_MODES),
  node_changes: Type.Array(DesignNodeChangeSchema),
  reused_assets: Type.Array(ReusedDesignAssetSchema),
  edge_changes: Type.Array(DesignEdgeChangeSchema),
  coverage: Type.Array(RequirementDesignCoverageSchema),
  risk_summary: DesignRiskSummarySchema,
  rationale: nonEmptyString,
});
export type DesignSetContent = Static<typeof DesignSetContentSchema>;

/** Run provenance: retained as evidence, never part of the content digest. */
export const DesignGeneratorProvenanceSchema = strictObject({
  port: Type.String({ minLength: 1, maxLength: 120 }),
  model: Type.Optional(Type.String({ minLength: 1, maxLength: 200 })),
  run_id: Type.Optional(IdentifierSchema),
  tokens: Type.Optional(Type.Integer({ minimum: 0 })),
  steps: Type.Optional(Type.Integer({ minimum: 0 })),
  duration_ms: Type.Optional(Type.Integer({ minimum: 0 })),
});
export type DesignGeneratorProvenance = Static<typeof DesignGeneratorProvenanceSchema>;

/**
 * The pre-approval runtime record (design 7.4). It lives under
 * `artifacts/design-set-proposals/` for resume, retry and approval audit;
 * it is never a graph fact.
 */
export const DesignSetProposalRecordSchema = recordEnvelopeSchema("design_set_proposal", {
  proposal_id: IdentifierSchema,
  workflow_operation_id: IdentifierSchema,
  iteration_id: IdentifierSchema,
  created_at: TimestampSchema,
  generator: DesignGeneratorProvenanceSchema,
  content: DesignSetContentSchema,
  content_digest: DigestSchema,
});
export type DesignSetProposalRecord = Static<typeof DesignSetProposalRecordSchema>;
