#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.

TOTAL_STAGES=8

banner "M3 三平台 dogfood 前置配置"

# ── Stage 1: 预检 ───────────────────────────────────────────────────────────
stage "预检"
say "M3-AC-13 需要在 GitHub / GitLab / Gitee 各跑一次真实 dogfood。"
say "每个平台需要：一个一次性测试仓库、一个 PAT、以及 harness/control"
say "分支的保护规则（只有 coordinator 身份可推送）。"
note "所有值写入仓库根目录的 .env（gitignored，dogfood 脚本会自动读取）。"
note "PAT 只用于本机运行，不会进入任何证据文件或提交。"
if [[ ! -d packages/runtime/dist || ! -d adapters/vcs-git/dist ]]; then
  warn "dist 构建产物缺失，dogfood 脚本运行在 dist/ 上。"
  confirm "现在运行 pnpm build（约一两分钟）？" && pnpm build
fi
pause "确认已了解，继续"

# ── Stage 2: GitHub ─────────────────────────────────────────────────────────
stage "GitHub — 仓库、PAT 与保护规则"
open_url "https://github.com/new"
step "创建一个一次性仓库（如 harness-m3-dogfood），Public/Private 均可。"
ask HARNESS_DOGFOOD_GITHUB_REPO "仓库 owner/repo（如 yourname/harness-m3-dogfood）："
open_url "https://github.com/settings/tokens/new"
step "创建 classic PAT，勾选 repo scope，过期时间选最短可用。"
step "（也可用 fine-grained PAT：只授权该仓库，Contents: Read and write。）"
ask_secret HARNESS_DOGFOOD_GITHUB_TOKEN "粘贴 GitHub PAT："
ask HARNESS_DOGFOOD_GITHUB_COORDINATOR_IDENTITY "coordinator 登录名（通常就是你的用户名）："
say "现在配置 harness/control 分支保护："
open_url "https://github.com/${HARNESS_DOGFOOD_GITHUB_REPO}/settings/branches"
step "组织仓库：Add classic branch protection rule，pattern 填 harness/control，"
step "  勾选 Restrict who can push 并只允许 coordinator 身份推送。"
step "个人仓库：GitHub 不支持 Restrict who can push（组织专属），改为"
step "  Add classic branch protection rule，pattern 填 harness/control，勾选"
step "  Do not allow force pushes、Do not allow deletions 与 Enforce admins，"
step "  并确认仓库没有其他协作者（Settings → Collaborators 只有 coordinator 本人）。"
warn "两种形态适配器都会验证；无法证明只有 coordinator 可推送时 dogfood 报告 blocked，不算失败。"
write_env HARNESS_DOGFOOD_GITHUB_REPO "$HARNESS_DOGFOOD_GITHUB_REPO"
write_env HARNESS_DOGFOOD_GITHUB_TOKEN "$HARNESS_DOGFOOD_GITHUB_TOKEN"
write_env HARNESS_DOGFOOD_GITHUB_COORDINATOR_IDENTITY "$HARNESS_DOGFOOD_GITHUB_COORDINATOR_IDENTITY"
pause "GitHub 配置完成后继续"

# ── Stage 3: GitLab ─────────────────────────────────────────────────────────
stage "GitLab — 项目、PAT 与保护分支"
open_url "https://gitlab.com/projects/new"
step "创建一个一次性项目（blank project，如 harness-m3-dogfood）。"
ask HARNESS_DOGFOOD_GITLAB_REPO "项目 owner/repo（如 yourname/harness-m3-dogfood）："
open_url "https://gitlab.com/-/user_settings/personal_access_tokens"
step "创建 PAT，勾选 api scope，过期时间选最近日期。"
ask_secret HARNESS_DOGFOOD_GITLAB_TOKEN "粘贴 GitLab PAT："
ask HARNESS_DOGFOOD_GITLAB_COORDINATOR_IDENTITY "coordinator 登录名（通常就是你的用户名）："
say "现在配置保护分支："
open_url "https://gitlab.com/${HARNESS_DOGFOOD_GITLAB_REPO}/-/settings/repository"
step "展开 Protected branches，分支填 harness/control（可预先不存在）。"
step "Allowed to push 只选 coordinator 用户本人（不要选角色/Maintainers）。"
step "Allowed to force push 保持关闭。"
write_env HARNESS_DOGFOOD_GITLAB_REPO "$HARNESS_DOGFOOD_GITLAB_REPO"
write_env HARNESS_DOGFOOD_GITLAB_TOKEN "$HARNESS_DOGFOOD_GITLAB_TOKEN"
write_env HARNESS_DOGFOOD_GITLAB_COORDINATOR_IDENTITY "$HARNESS_DOGFOOD_GITLAB_COORDINATOR_IDENTITY"
pause "GitLab 配置完成后继续"

# ── Stage 4: Gitee ──────────────────────────────────────────────────────────
stage "Gitee — 仓库、PAT 与保护分支"
open_url "https://gitee.com/projects/new"
step "创建一个一次性仓库（如 harness-m3-dogfood）。"
ask HARNESS_DOGFOOD_GITEE_REPO "仓库 owner/repo（如 yourname/harness-m3-dogfood）："
open_url "https://gitee.com/profile/personal_access_tokens"
step "创建私人令牌（PAT），勾选 projects 相关权限，过期时间选最短。"
ask_secret HARNESS_DOGFOOD_GITEE_TOKEN "粘贴 Gitee PAT："
ask HARNESS_DOGFOOD_GITEE_COORDINATOR_IDENTITY "coordinator 登录名（通常就是你的用户名）："
say "现在配置保护分支："
open_url "https://gitee.com/${HARNESS_DOGFOOD_GITEE_REPO}/protected_branches"
step "新建保护分支规则，分支填 harness/control。"
step "推送者（pusher）只设 coordinator 本人；禁止强推。"
warn "若界面文案与上述不同（Gitee UI 可能更新），以保护分支 + 指定推送者为准。"
warn "若无法证明只有 coordinator 可推送，dogfood 会报告 blocked，不算失败。"
write_env HARNESS_DOGFOOD_GITEE_REPO "$HARNESS_DOGFOOD_GITEE_REPO"
write_env HARNESS_DOGFOOD_GITEE_TOKEN "$HARNESS_DOGFOOD_GITEE_TOKEN"
write_env HARNESS_DOGFOOD_GITEE_COORDINATOR_IDENTITY "$HARNESS_DOGFOOD_GITEE_COORDINATOR_IDENTITY"
pause "Gitee 配置完成后继续"

# ── Stage 5-7: 逐平台运行 dogfood ───────────────────────────────────────────
run_dogfood() {
  local provider="$1"
  stage "运行 dogfood — ${provider}"
  say "命令：node scripts/dogfood-m3-platform.mjs --provider ${provider}"
  note "exit 0 = passed；exit 2 = blocked（前置/保护不可证明）；exit 1 = failed。"
  if confirm "现在运行 ${provider} dogfood？"; then
    node scripts/dogfood-m3-platform.mjs --provider "$provider" || true
    note "证据 bundle 已写入 docs/evidence/m3-dogfood-${provider}.json（不含 token）。"
  else
    SKIPPED+=("dogfood ${provider}（稍后手动运行：node scripts/dogfood-m3-platform.mjs --provider ${provider}）")
  fi
}
run_dogfood github
run_dogfood gitlab
run_dogfood gitee

# ── Stage 8: 重生验收报告 ───────────────────────────────────────────────────
stage "重新生成验收报告"
say "三平台 bundle 到位后，重新生成验收报告以刷新 M3-AC-13/14。"
if confirm "现在运行 node scripts/generate-acceptance-report.mjs？"; then
  node scripts/generate-acceptance-report.mjs || true
  note "报告已更新：docs/evidence/m3-remote-collaboration-completion.md"
  note "三平台 dogfood 通过后，请提交证据并摘除 README 的'开发中'标注。"
fi

finish
